//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public string Country { get; set; }
        public string DomainName { get; set; }
        public string GroupId { get; set; }
        public string ImageUrl { get; set; }
        public bool IsPopularWebsite { get; set; }
        public string Lang { get; set; }
        public long NewsId { get; set; }
        public bool OnHomePage { get; set; }
        public string PublishDate { get; set; }
        public int RetweetCount { get; set; }
        public string Spot { get; set; }
        public string Title { get; set; }
        public string Topics { get; set; }
        public string Url { get; set; }
        public int Id { get; set; }
    }
}
